version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    #            target: development
    ports:
      - 8080:8080
      - 4000:4000
    volumes:
      - ./:/app
    # command: npm run serve
    # command: >
    #   ash -c 'npm install; npm run dev'

    tty: true
    # depends_on:
    #   - json-server

  # json-server:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.js
  #   ports:
  #     - '3000:3000'
  #   volumes: 
  #     - ./data/db.json:/data/db.json
  #   command: json-server --watch db.json --host 0.0.0.0
  #   tty: true
